"""Run once to generate PWA icons into static/icons/"""
import os, struct, zlib, math

def make_png(size):
    """Generate a gradient + calendar emoji icon as PNG bytes using only stdlib."""
    # We'll create the icon via HTML canvas in the browser instead.
    # This script is a fallback — see templates/index.html for the canvas approach.
    pass

# Use Pillow if available, otherwise skip (icons generated by canvas at runtime)
try:
    from PIL import Image, ImageDraw, ImageFont
    HAS_PILLOW = True
except ImportError:
    HAS_PILLOW = False

os.makedirs('static/icons', exist_ok=True)

if HAS_PILLOW:
    for size in [192, 512]:
        img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)

        # Gradient background with rounded corners
        radius = int(size * 0.22)
        for y in range(size):
            t = y / size
            r = int(124 + (236 - 124) * t)
            g = int(106 + (72 - 106) * t)
            b = int(247 + (153 - 247) * t)
            draw.rectangle([(0, y), (size, y + 1)], fill=(r, g, b, 255))

        # Rounded mask
        mask = Image.new('L', (size, size), 0)
        mask_draw = ImageDraw.Draw(mask)
        mask_draw.rounded_rectangle([(0, 0), (size - 1, size - 1)], radius=radius, fill=255)
        img.putalpha(mask)

        # Calendar emoji — draw a simple calendar shape
        pad = int(size * 0.15)
        cw = size - pad * 2
        ch = int(cw * 0.85)
        cy = int(size * 0.2)
        cx = pad

        # Card body
        draw.rounded_rectangle([(cx, cy), (cx + cw, cy + ch)], radius=int(size * 0.06), fill=(255, 255, 255, 220))
        # Header bar
        draw.rounded_rectangle([(cx, cy), (cx + cw, cy + int(ch * 0.28))], radius=int(size * 0.06), fill=(124, 106, 247, 255))
        # Grid dots (days)
        cols, rows_g = 4, 3
        gpad = int(cw * 0.1)
        gx0 = cx + gpad
        gy0 = cy + int(ch * 0.35)
        gw = (cw - gpad * 2) / cols
        gh = (ch * 0.55) / rows_g
        dot_r = max(int(size * 0.025), 3)
        colors = [(124, 106, 247, 200), (236, 72, 153, 200), (62, 207, 142, 200), (245, 158, 11, 200)]
        for row in range(rows_g):
            for col in range(cols):
                dx = int(gx0 + col * gw + gw / 2)
                dy = int(gy0 + row * gh + gh / 2)
                c_idx = (row * cols + col) % len(colors)
                draw.ellipse([(dx - dot_r, dy - dot_r), (dx + dot_r, dy + dot_r)], fill=colors[c_idx])

        img.save(f'static/icons/icon-{size}.png', 'PNG')
        print(f'Generated static/icons/icon-{size}.png')

    # Apple touch icon at 180x180
    img = Image.open('static/icons/icon-192.png').resize((180, 180), Image.LANCZOS)
    img.save('static/icons/apple-touch-icon.png', 'PNG')
    print('Generated static/icons/apple-touch-icon.png')

else:
    print('Pillow not installed. Icons will be generated by canvas in the browser.')
    print('Install with: pip install Pillow')
    print('Or the app works fine without it — canvas icons are used as fallback.')
